#!/bin/bash
cd /mnt/c/Users/TRS/desktop/Rustchain_Repo_Scaffold
mkdir -p nfts
mkdir -p badges
mkdir -p tools
mkdir -p docs
mv nft_badge_ppc_flame_valve.json nfts/
git add nfts/nft_badge_ppc_flame_valve.json
mv nft_badge_vickimac_flamekeeper.json nfts/
git add nfts/nft_badge_vickimac_flamekeeper.json
mv nft_badge_museum_relic.json nfts/
git add nfts/nft_badge_museum_relic.json
mv nft_badge_runs_doom.json nfts/
git add nfts/nft_badge_runs_doom.json
mv nft_badge_dos_wifi_alchemist.json nfts/
git add nfts/nft_badge_dos_wifi_alchemist.json
mv nft_badge_ham_radio_validator.json nfts/
git add nfts/nft_badge_ham_radio_validator.json
mv nft_badge_quickbasic_listener.json nfts/
git add nfts/nft_badge_quickbasic_listener.json
mv nft_badge_gravis_reclaimer.json nfts/
git add nfts/nft_badge_gravis_reclaimer.json
mv nft_badge_pawpaw_bios_flame.json nfts/
git add nfts/nft_badge_pawpaw_bios_flame.json
mv badge_pawpaw_legacy_miner.json badges/
git add badges/badge_pawpaw_legacy_miner.json
mv badge_motorola_68k_flamecarver.json badges/
git add badges/badge_motorola_68k_flamecarver.json
mv badge_motorola_m88k_archivist.json badges/
git add badges/badge_motorola_m88k_archivist.json
mv badge_ppc_flame_valve_v2.json badges/
git add badges/badge_ppc_flame_valve_v2.json
mv badge_qb45_validator.json badges/
git add badges/badge_qb45_validator.json
mv badge_reclaimer_of_the_guilty_sparc.json badges/
git add badges/badge_reclaimer_of_the_guilty_sparc.json
mv badge_sparc_flame_reclaimer.json badges/
git add badges/badge_sparc_flame_reclaimer.json
mv badge_uber_dev_forge.json badges/
git add badges/badge_uber_dev_forge.json
mv badge_vickimac_flamekeeper.json badges/
git add badges/badge_vickimac_flamekeeper.json
mv bios_pawpaw_detector.py tools/
git add tools/bios_pawpaw_detector.py
mv gpu_display_detector.py tools/
git add tools/gpu_display_detector.py
mv os_detector.py tools/
git add tools/os_detector.py
mv rustchain_basic_listener_with_proof.py tools/
git add tools/rustchain_basic_listener_with_proof.py
mv rustchain_packet_radio_sender.py tools/
git add tools/rustchain_packet_radio_sender.py
mv rustchain_packet_radio_validator.py tools/
git add tools/rustchain_packet_radio_validator.py
mv RustChain_Whitepaper_Flameholder_v0.97-1.pdf docs/
git add docs/RustChain_Whitepaper_Flameholder_v0.97-1.pdf
git add "README.md"
git add ".gitignore"
git add "anti_vm.py"
git add "ergo_wrapper.py"
git add "leaderboard.json"
git add "proof_of_antiquity.json"
git add "relic_rewards.json"
git add "validator_core.py"
git add "validator_core_with_badge.py"
git add "weighted_decryption.py"
git add "dev_bounties.json"
git add "nft_asset_manifest.json"
git add "RUSTVAL.BAS"
git add "update_git_rustchain.sh"
git commit -m "Restructured repo with organized folders and synced all badge/NFT/tool files"
git push origin main