#!/bin/bash
cd /mnt/c/Users/TRS/desktop/Rustchain_Repo_Scaffold
git add "nft_badge_ppc_flame_valve.json"
git add "nft_badge_vickimac_flamekeeper.json"
git add "nft_badge_museum_relic.json"
git add "nft_badge_runs_doom.json"
git add "nft_badge_dos_wifi_alchemist.json"
git add "nft_badge_ham_radio_validator.json"
git add "nft_badge_quickbasic_listener.json"
git add "nft_badge_gravis_reclaimer.json"
git add "nft_badge_pawpaw_bios_flame.json"
git add "README.md"
git add "RustChain_Whitepaper_Flameholder_v0.97-1.pdf"
git add "anti_vm.py"
git add "bios_pawpaw_detector.py"
git add "ergo_wrapper.py"
git add "leaderboard.json"
git add "proof_of_antiquity.json"
git add "relic_rewards.json"
git add "validator_core.py"
git add "weighted_decryption.py"
git commit -m "Synced all NFT JSONs and core RustChain updates from local root directory"
git push origin main