#!/bin/bash
#
# RIP-302 CI/CD Validation Script
#
# This script validates RIP-302 challenge submissions in CI/CD pipelines.
# It runs the challenge, verifies evidence, and generates a validation report.
#
# Usage:
#   ./ci_validate.sh                    # Run full validation
#   ./ci_validate.sh --skip-run         # Skip challenge run, only verify
#   ./ci_validate.sh --scenario heartbeat  # Run specific scenario
#
# Exit codes:
#   0 - All validations passed
#   1 - Validation failed
#   2 - Configuration error
#

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHALLENGE_DIR="$(dirname "$SCRIPT_DIR")"
EVIDENCE_DIR="$CHALLENGE_DIR/evidence"
OUTPUT_DIR="$CHALLENGE_DIR/.ci_output"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Parse arguments
SKIP_RUN=false
SCENARIO=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-run)
            SKIP_RUN=true
            shift
            ;;
        --scenario)
            SCENARIO="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--skip-run] [--scenario <name>]"
            echo ""
            echo "Options:"
            echo "  --skip-run    Skip challenge execution, only verify existing evidence"
            echo "  --scenario    Run only the specified scenario"
            echo "  --help        Show this help message"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 2
            ;;
    esac
done

# Create output directory
mkdir -p "$OUTPUT_DIR"

log_info "RIP-302 CI/CD Validation"
log_info "========================"
log_info "Challenge Directory: $CHALLENGE_DIR"
log_info "Evidence Directory: $EVIDENCE_DIR"
log_info "Output Directory: $OUTPUT_DIR"
echo ""

# Step 1: Run challenge (if not skipped)
if [ "$SKIP_RUN" = false ]; then
    log_info "Step 1: Running challenge scenarios..."
    
    cd "$CHALLENGE_DIR"
    
    if [ -n "$SCENARIO" ]; then
        log_info "Running scenario: $SCENARIO"
        python3 "$SCRIPT_DIR/run_challenge.py" --scenario "$SCENARIO" --output "$EVIDENCE_DIR" --mock
    else
        log_info "Running all scenarios"
        python3 "$SCRIPT_DIR/run_challenge.py" --all --output "$EVIDENCE_DIR" --mock
    fi
    
    if [ $? -ne 0 ]; then
        log_error "Challenge execution failed"
        exit 1
    fi
    
    log_info "Challenge execution completed"
else
    log_warn "Step 1: Skipping challenge execution (--skip-run)"
fi

echo ""

# Step 2: Verify evidence
log_info "Step 2: Verifying evidence..."

python3 "$SCRIPT_DIR/verify_evidence.py" \
    --evidence-dir "$EVIDENCE_DIR" \
    --output "$OUTPUT_DIR/verification_report.json"

if [ $? -ne 0 ]; then
    log_error "Evidence verification failed"
    exit 1
fi

log_info "Evidence verification passed"
echo ""

# Step 3: Collect proof
log_info "Step 3: Collecting proof bundle..."

python3 "$SCRIPT_DIR/collect_proof.py" \
    --evidence-dir "$EVIDENCE_DIR" \
    --output "$OUTPUT_DIR/proof_bundle.json" \
    --include-metadata

if [ $? -ne 0 ]; then
    log_error "Proof collection failed"
    exit 1
fi

log_info "Proof bundle collected"
echo ""

# Step 4: Generate summary report
log_info "Step 4: Generating summary report..."

cat > "$OUTPUT_DIR/summary.md" << EOF
# RIP-302 CI/CD Validation Summary

**Timestamp:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**Validation Run:** $(basename "$OUTPUT_DIR")

## Results

### Challenge Execution
- Status: $([ "$SKIP_RUN" = false ] && echo "✓ Completed" || echo "⊘ Skipped")
- Scenarios: ${SCENARIO:-all}

### Evidence Verification
- Status: ✓ Passed
- Report: verification_report.json

### Proof Collection
- Status: ✓ Completed
- Bundle: proof_bundle.json

## Artifacts

All validation artifacts are available in: \`$OUTPUT_DIR\`

- \`verification_report.json\` - Detailed verification results
- \`proof_bundle.json\` - Complete proof bundle for submission
- \`summary.md\` - This summary file

## Next Steps

1. Review the verification report for any warnings
2. Download the proof bundle for bounty submission
3. Reference this validation run in your bounty claim

---

*Generated by RIP-302 CI/CD Validation Script*
EOF

log_info "Summary report generated: $OUTPUT_DIR/summary.md"
echo ""

# Final status
log_info "========================"
log_info "✓ ALL VALIDATIONS PASSED"
log_info "========================"
log_info "Artifacts available in: $OUTPUT_DIR"

exit 0
