package com.rustchain.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents the Proof of Antiquity JSON structure used by RustChain validators.
 * This file is generated by validators to prove they are running on vintage hardware.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProofOfAntiquity {

    @JsonProperty("validator_id")
    private String validatorId;

    @JsonProperty("timestamp")
    private long timestamp;

    @JsonProperty("hardware_fingerprint")
    private HardwareFingerprint hardwareFingerprint;

    @JsonProperty("entropy_proof")
    private EntropyProof entropyProof;

    @JsonProperty("attestation")
    private Attestation attestation;

    @JsonProperty("score")
    private Score score;

    @JsonProperty("metadata")
    private Metadata metadata;

    public ProofOfAntiquity() {
    }

    // Getters and Setters
    public String getValidatorId() {
        return validatorId;
    }

    public void setValidatorId(String validatorId) {
        this.validatorId = validatorId;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public HardwareFingerprint getHardwareFingerprint() {
        return hardwareFingerprint;
    }

    public void setHardwareFingerprint(HardwareFingerprint hardwareFingerprint) {
        this.hardwareFingerprint = hardwareFingerprint;
    }

    public EntropyProof getEntropyProof() {
        return entropyProof;
    }

    public void setEntropyProof(EntropyProof entropyProof) {
        this.entropyProof = entropyProof;
    }

    public Attestation getAttestation() {
        return attestation;
    }

    public void setAttestation(Attestation attestation) {
        this.attestation = attestation;
    }

    public Score getScore() {
        return score;
    }

    public void setScore(Score score) {
        this.score = score;
    }

    public Metadata getMetadata() {
        return metadata;
    }

    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    @Override
    public String toString() {
        return "ProofOfAntiquity{" +
                "validatorId='" + validatorId + '\'' +
                ", timestamp=" + timestamp +
                ", score=" + (score != null ? score.getTotalScore() : "N/A") +
                '}';
    }
}
